docs-ref-conceptual/index.md
Small front page wording changes.
=> slight front page wording changes

docs-ref-conceptual/index.md
This method does not a return a server, but an async poller object for server. The variable is misleading, it's better to say nothing.
=> Remove server variable

docs-ref-mapping/reference.yml, docs-ref-services/authorization.md, docs-ref-services/billing.md, docs-ref-services/cdn.md, docs-ref-services/cognitive-services.md, docs-ref-services/commerce.md, docs-ref-services/consumption.md, docs-ref-services/container-registry.md, docs-ref-services/data-lake-analytics.md, docs-ref-services/data-lake-store.md, docs-ref-services/devtest-labs.md, docs-ref-services/dns.md, docs-ref-services/event-hub.md, docs-ref-services/graph.md, docs-ref-services/iot.md, docs-ref-services/logic-apps.md, docs-ref-services/media-services.md, docs-ref-services/monitoring.md, docs-ref-services/network.md, docs-ref-services/notification-hubs.md, docs-ref-services/other.md, docs-ref-services/power-bi.md, docs-ref-services/recovery-services-backup.md, docs-ref-services/resources.md, docs-ref-services/scheduler.md, docs-ref-services/search.md, docs-ref-services/server-manager.md, docs-ref-services/traffic-manager.md
=> - Add auto-generated landing stubs for reference pages.

docs-ref-conceptual/python-sdk-azure-samples-managed-disks.md
@lisawong19, 
Could you help to merge this PR, please? There is conten blocked for localization.
Many thanks.
=> M11075: Content blocked for localization: "article" - LOCBLOCKER

docs-ref-conceptual/python-sdk-azure-samples-managed-disks.md
Hello, @lisawong19, 
It seems that there is a typo mistake at the end of the sentence. Could you help to review this and merge, please?
=> M12517: Extra "__" at the end of the sentence

docs-ref-mapping/reference.yml, docs-ref-services/monitoring.md
azure-mgmt-monitor 0.4.0 released today
=> Adapt sample page for merged Monitor

docs-ref-services/network.md
Original link referenced this path: https://docs.microsoft.com/en-us/python/api/overview/azure/[https://azure.microsoft.com/en-us/resources/samples/network-python-manage-loadbalancer/]?view=azure-python
Modified the link to address the correct path.
=> Update "Getting Started" Link

docs-ref-conceptual/python-sdk-azure-get-started.yml
https://mseng.visualstudio.com/CSI/_workitems/edit/1163018
=> fix tutorial yml

docs-ref-services/sql.md
Updated the code to reflect module imports.
Updated the code to create a SQL server and a SQL DB.
Fixed typo for adding the firewall rule.
=> Update SQL DB creation code

docs-ref-conceptual/python-sdk-azure-authenticate.md
Hello, @lisawong19 ,
This proposed file change comes from https://github.com/MicrosoftDocs/azure-docs-sdk-python.fr-FR/pull/4. 
Could you review this contribution and help to merge if agreed?
=> CC58322: comma removed in code.

docs-ref-conceptual/index.yml
Closes https://github.com/MicrosoftDocs/feedback/issues/428
=> typo: Comos -> Cosmos

docs-ref-services/authorization.md
Hello, @lisawong19 ,
This proposed file change comes from https://github.com/MicrosoftDocs/azure-docs-sdk-python.fr-FR/pull/3 . 
Could you review this contribution and help to merge if agreed?
=> CC58301: Comma removed

docs-ref-services/key-vault.md
Hello, @lisawong19 ,
This proposed file change comes from https://github.com/MicrosoftDocs/azure-docs-sdk-python.fr-FR/pull/2 . 
Could you review this contribution and help to merge if agreed?
=> CC58295, 58296

docs-ref-services/storage.md
Adds import statement to example script.
=> Updates example in azure blob storage docs

docs-ref-services/activedirectory.md
Removing ms.service:active-directory from metadata based on this report: https://msit.powerbi.com/groups/me/reports/58580efe-c697-4e20-a7dd-88908d4af9ae/ReportSection64c0fd9156f2b8cc3fe8
=> Remove ms.service:active-directory from metadata

docs-ref-conceptual/index.yml
@rabee333  can you review these changes?
=> change icons and app service link

docs-ref-services/servicebus.md
FYI @lmazuel, @johanste, @mmacy, @binderjoe 
Reviews would be much appreciated!!
=> Updates to ServiceBus SDK overview

docs-ref-services/postgresql-mysql.md
Hello, @lisawong19,
This proposed file change comes from https://github.com/MicrosoftDocs/azure-docs-sdk-python.es-ES/pull/3 .
Could you review this contribution and help to merge if agreed?
=> CC91861: Typo

docs-ref-services/key-vault.md
Removes unused code from examples and increases the consistency to make them easier to read.
Also adds an example of retrieving a property from the result of the "create" operation
=> Improve key vault examples

docs-ref-services/containerinstance.md
See https://github.com/Azure-Samples/aci-docs-sample-python/pull/3
=> Updated script line numbers per customer PR

docs-ref-mapping/reference.yml, docs-ref-services/graph-rbac.md
=> rearrange python ref to show graph rbac separate from Azure Identity

docs-ref-services/cdn.md
=> Update documentation example

docs-ref-conceptual/python-sdk-azure-get-started.yml, docs-ref-conceptual/python-sdk-azure-overview.md, docs-ref-services/cognitive-services.md, docs-ref-services/containerinstance.md, docs-ref-services/event-grid.md, docs-ref-services/graph-rbac.md, docs-ref-services/postgresql-mysql.md, docs-ref-services/sql.md
This PR fixes the following issues for User Story https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1549006, Address CATS content quality issues for content linked from Python dev center:
- Broken external links
- Broken internal links
- Broken bookmarks
- HTTPS checking
- Missing page info (publish time)
=> Fix CATS issues per User Story #1549006

docs-ref-services/cognitive-services.md, docs-ref-services/hdinsight.md
This PR fixes the "Missing language spec" issue for User Story https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1549006, Address CATS content quality issues for content linked from Python dev center.
=> Fix CATS code language label issue per User Story #1549006

.openpublishing.publish.config.json, .openpublishing.redirection.json, docfx.json, docs-ref-conceptual/index.md
Need to publish to fix a redirect 404 issue.
=> Manual publish 8/30 PM

docs-ref-services/batchai.md
Rebranding of Azure Machine Learning per User Story https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1624627.
=> US 1624627 - Rebranding for Azure Machine Learning

docs-ref-mapping/reference.yml, docs-ref-services/storage-blob-readme.md, docs-ref-services/storage-fileshare-readme.md, docs-ref-services/storage-index.md, docs-ref-services/storage-queue-readme.md
* update storage index to v12
* Add readmes from blob, file share, queue
* update ToC to include readmes
* fix ToC list, update headers to include readme
* flatten ToC, update readmes to match style guide
* fix capitals
=> Update storage to match SDK docs guidelines (#612)

docs-ref-services/batch.md
Move client API button to the correct place
=> Move client API button to the correct place

docs-ref-services/key-vault-index.md, docs-ref-services/key-vault.md
Update the Key Vault index pages on docs.microsoft.com for python with reference to the link
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet
=> Update the Key Vault index pages on docs.microsoft.com for python

docs-ref-mapping/reference-preview.yml
Hi Scott, this PR is to add Track 2 packages to python preview TOC tree
=> Add Track 2 packages to Preview TOC tree

docs-ref-services/servicebus.md
resolves MicrosoftDocs/azure-docs#53580
=> (Azure CXP) Async samples to be more discover-able

docs-ref-mapping/reference-unified.yml
Changed to data-tables-readme.md. PR to different branch
=> Smoke test tables

docs-ref-mapping/reference-unified.yml
I'm not sure what I'm doing here, trying to follow the primer, feel free to tell if I miss something @scbedd
=> Anomaly Detector

docs-ref-mapping/reference-unified.yml
Adds the reference toc items for ACS.
=> feat(acs): add ref toc items for ACS

docs-ref-services/identity-readme.md
Not even going to wait for build on this one 👍
=> Bump Readme Version

docs-ref-mapping/reference-unified.yml
- Updating reference docs index for new service - metrics advisor
=> add metrics advisor to reference index

.openpublishing.redirection.json, docs-ref-services/latest/keyvault-certificates-readme.md, docs-ref-services/latest/keyvault-keys-readme.md, docs-ref-services/latest/keyvault-secrets-readme.md, docs-ref-services/preview/keyvault-certificates-readme.md, docs-ref-services/preview/keyvault-keys-readme.md, docs-ref-services/preview/keyvault-secrets-readme.md
Resolves Azure/azure-sdk-for-python/issues/15796.
This also brings the package overviews up to date with azure-sdk-for-python READMEs.
=> Add redirect for broken link, update package overviews

docs-ref-services/latest/cdn.md, docs-ref-services/latest/hdinsight.md, docs-ref-services/latest/keyvault-secrets-readme.md, docs-ref-services/latest/resources.md, docs-ref-services/latest/search-documents-readme.md, docs-ref-services/legacy/cdn.md, docs-ref-services/legacy/hdinsight.md, docs-ref-services/legacy/keyvault-secrets-readme.md, docs-ref-services/legacy/resources.md, docs-ref-services/legacy/search-documents-readme.md, docs-ref-services/preview/cdn.md, docs-ref-services/preview/core-tracing-opencensus-readme.md, docs-ref-services/preview/eventhub-readme.md, docs-ref-services/preview/hdinsight.md, docs-ref-services/preview/keyvault-certificates-readme.md, docs-ref-services/preview/keyvault-keys-readme.md, docs-ref-services/preview/keyvault-secrets-readme.md, docs-ref-services/preview/resources.md
Anyone notified by GitHub: this is for [user story 1812099](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1812099).
Addresses hard coded locales.
We are fixing issues related to Accessibility, SEO, and code blocks. You are welcome to review this PR, but for these changes, you don't need to sign off.
This is a bulk update.
Thanks -
=> Message Fixes: User Story 1812099 - BULK

ci-configs/packages-latest.json, ci-configs/packages-preview.json, docs-ref-services/latest/mgmt-confluent-readme.md, docs-ref-services/preview/keyvault-keys-readme.md
=> Feb release fixes

docs-ref-services/latest/sql.md
https://docs.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python
#PingMSFTDocs
=> Typo "Azure SQL database"→"Azure SQL Database"

docfx.json
Enables the scoped search feature to filter search results to Azure content
=> Scope ref search to Azure content

docs-ref-mapping/reference-preview.yml, docs-ref-mapping/reference-unified.yml
To ensure it shows up in the main ToC.
=> ToC updates for testbase

ci-configs/packages-latest.json, ci-configs/packages-preview.json
minus those in https://github.com/Azure/azure-sdk-for-python/issues/17651
=> Onboard for packages for publish 

ci-configs/packages-latest.json
=> target dist file instead of official pypi version

docs-ref-services/latest/containerinstance.md, docs-ref-services/legacy/containerinstance.md, docs-ref-services/preview/containerinstance.md
So that the sample of cleaning up includes the necessary line of code.
=> Update Containerinstance Docs 

ci-configs/packages-preview.json
…ocs)"
This reverts commit 64a78ed2cc8b75f5373398bae7d8461314ba2c38.
=> revert some override field

ci-configs/packages-latest.json, ci-configs/packages-preview.json
This reverts commit 70a1f3fc8100066b43be3ab8fe661846a0d35679.
=> Revert "Update docs CI configuration"

ci-configs/packages-preview.json
=> Remove azure-mgmt-videoanalyzer

ci-configs/packages-latest.json, ci-configs/packages-preview.json
Now with fewer merge conflicts
=> Pin packages that PyPI will not fetch in Python 3.6

docfx.json
Addresses https://github.com/Azure/azure-sdk-for-net/issues/27450
=> Define explicit product feedback link for Azure SDK for Python

.openpublishing.redirection.json
@danieljurek [Related to this issue](https://github.com/Azure/azure-sdk-for-python/issues/24128)
I hunted down the reason that I think this service overview isn't rendering.
=> Remove `key-vault.md` redirection setting

.openpublishing.redirection.json, docs-ref-autogen/azure-datalake-store/azure.datalake.store.lib.DatalakeRESTInterface.yml, docs-ref-autogen/msal/msal.oauth2cli.oauth2.Client.yml, docs-ref-autogen/msal/msal.oauth2cli.oidc.Client.yml, docs-ref-autogen/msrest/msrest.serialization.Model.yml
One change to .json file in root: .openpublishing.redirection.json
=> Merge to live 2022-04-27

ci-configs/packages-latest.json
DPS provisioning service client never was produced.  Removing docs.
=> (chore): remove the dps provisioning service client

ci-configs/packages-latest.json, docs-ref-autogen/azure-datalake-store/azure.datalake.store.lib.DatalakeRESTInterface.yml, docs-ref-autogen/msal/msal.oauth2cli.oauth2.Client.yml, docs-ref-autogen/msal/msal.oauth2cli.oidc.Client.yml, docs-ref-autogen/msrest/msrest.serialization.Model.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.aio.operations.MongoDBResourcesOperations.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.aio.operations.SqlResourcesOperations.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.PhysicalPartitionThroughputInfoProperties.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.PhysicalPartitionThroughputInfoResult.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.PhysicalPartitionThroughputInfoResultPropertiesResource.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.models.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.operations.MongoDBResourcesOperations.yml, preview/docs-ref-autogen/azure-mgmt-cosmosdb/azure.mgmt.cosmosdb.operations.SqlResourcesOperations.yml, preview/docs-ref-autogen/toc.yml
No detected changes to .json files in the root
=> Merge to live 2022-05-25

docs-ref-services/latest/azure.mgmt.resource.md
fix: https://github.com/Azure/azure-sdk-for-python/issues/24387
=> [Resources] Fix broken links in Azure Resources libraries

ci-configs/packages-latest.json, ci-configs/packages-preview.json, docs-ref-autogen/azure-datalake-store/azure.datalake.store.lib.DatalakeRESTInterface.yml, docs-ref-autogen/azure-eventgrid/azure.eventgrid.EventGridPublisherClient.yml, docs-ref-autogen/azure-eventgrid/azure.eventgrid.aio.EventGridPublisherClient.yml, docs-ref-autogen/msrest/msrest.serialization.Model.yml, docs-ref-mapping/reference-preview.yml, docs-ref-mapping/reference.yml, docs-ref-services/latest/eventgrid-readme.md, docs-ref-services/latest/mgmt-storagecache-readme.md, docs-ref-services/latest/servicebus-readme.md, docs-ref-services/preview/iot-deviceupdate-readme.md, docs-ref-services/preview/mgmt-education-readme.md, docs-ref-services/preview/mgmt-loganalytics-readme.md, docs-ref-services/preview/mgmt-sql-readme.md, metadata/latest/azure-eventgrid.json, metadata/latest/azure-mgmt-storagecache.json, metadata/latest/azure-servicebus.json, metadata/preview/azure-iot-deviceupdate.json, metadata/preview/azure-mgmt-education.json, metadata/preview/azure-mgmt-loganalytics.json, metadata/preview/azure-mgmt-sql.json, preview/docs-ref-autogen/azure-identity/azure.identity.EnvironmentCredential.yml, preview/docs-ref-autogen/azure-identity/azure.identity.aio.EnvironmentCredential.yml, xrefmap.yml
No detected changes to .json files in the root
=> Merge to live 2022-07-07

docs-ref-services/latest/consumption.md
resolves Azure/azure-sdk-for-python#25283
=> Fix explore link

docs-ref-services/latest/authorization.md
fixes Azure/azure-sdk-for-python#25739
Explore the Management APIs button link is broken in this artcile:
Docs Link: https://docs.microsoft.com/en-us/python/api/overview/azure/authorization?view=azure-python
Old Link: https://docs.microsoft.com/en-us/python/api/overview/azure/authorization/management New Link: https://docs.microsoft.com/en-us/python/api/overview/azure/mgmt-authorization-readme?view=azure-python
This PR fixes this link.
=> {AuthorizationManagement} fixes Azure/azure-sdk-for-python#25739

docs-ref-services/latest/power-bi.md
fixes Azure/azure-sdk-for-python#28895
This PR includes the fix for broken management APIs link.
Old Link: /python/api/overview/azure/powerbi/management/resourcemanagement-powerbiembedded
New Link: /python/api/overview/azure/powerbiembedded/management/resourcemanagement-powerbiembedded
=> {AzurePowerBI} fixes Azure/azure-sdk-for-python#28895 Fix for broken management APIs link

docs-ref-services/preview/communication-email-readme.md
resolves Azure/azure-sdk-for-python#28408
=> Fix typo in get_send_status method name

ci-configs/packages-latest.json
Reverts MicrosoftDocs/azure-docs-sdk-python#1729
=> Revert "Pull azure-functions and azure-functions-durable from PyPI"

docs-ref-services/preview/ai-contentsafety-readme.md
Fixing tables that don't render properly on MS Learn
=> Fix Content Safety docs

docs-ref-services/latest/batch.md
- Update Batch overview page to align with current service.
- Replace deprecated reference links with accessible new ones.
=> Update Batch overview page

ci-configs/packages-preview.json, metadata/preview/azure-cognitiveservices-search-autosuggest.json
Package should now be present in artifact feed
=> Re-add azure-cognitiveservies-search-autosuggest

docs-ref-autogen/azure-servicebus/azure.servicebus.ServiceBusMessage.yml
closes https://github.com/Azure/azure-sdk-for-python/issues/30802
=> [ServiceBus] Update azure.servicebus.ServiceBusMessage.yml

docs-ref-services/latest/resources.md
fix https://github.com/Azure/azure-sdk-for-python/issues/30987
=> [Mgmt] Update resources.md

ci-configs/packages-latest.json, ci-configs/packages-legacy.json, ci-configs/packages-preview.json
Related tasks: 
1. https://dev.azure.com/ceapex/Engineering/_workitems/edit/600528
2. https://dev.azure.com/ceapex/Engineering/_workitems/edit/863587
=> Enable inherited-member config for non azure-mgmt package

docs-ref-services/latest/communication-email-readme.md
closes https://github.com/Azure/azure-sdk-for-python/issues/30995
=> [Communication] Update communication-email-readme.md

docfx.json
Includes feedback control changes
=> Merge to live 2023-12-13

metadata/preview/azure-servicemanagement-legacy.json
Manually update the full set of namespaces for azure-servicemanagement-legacy as per what's in the [work item](https://dev.azure.com/ceapex/Engineering/_workitems/edit/950573?src=WorkItemMention&src-action=artifact_link)
=> Update namespaces for azure-servicemanagement-legacy

metadata/latest/azure-communication-messages.json
add namespace to latest\azure-communication-messages.json file
=> Add namespace to azure-communication-messages

metadata/latest/azure-mgmt-iotfirmwaredefense.json, metadata/latest/azure-mgmt-sphere.json
The PR for python was delayed being checked in due to an ask. In that PR namespaces get added to the json file and those are used in index processing. This PR just adds namespaces to new libraries that were released prior to the PR being checked in.
=> Add namespaces for libraries released before the Python update PR was merged

docs-ref-services/latest/compute.md
fix broken links mentioned in https://github.com/Azure/azure-sdk-for-python/issues/37361
=> Update compute.md to fix broken links

docfx.json, docs-ref-services/latest/data-lake-storage-(gen-2).md, docs-ref-services/latest/red-hat-openshift-(aro).md, docs-ref-services/preview/data-lake-storage-(gen-2).md, docs-ref-services/preview/red-hat-openshift-(aro).md
See https://dev.azure.com/ceapex/Engineering/_workitems/edit/853550 and https://github.com/Azure/azure-sdk-tools/issues/5433
Fixes INCLUDEs broken due to lack of escaping and adds exclude config for -index.md files.
Additional changes are needed in the upstream shared code to ensure that filenames of new readmes have the proper escaping put in place.
=> Fix broken INCLUDEs and add -index.md build exclusions
