MicrosoftDocs/azure-docs-sdk-python

docs-ref-conceptual/python-sdk-azure-authenticate.md

- Change the title level, so we get a usuable right column (today it's pointless)
- Move ServicePrincipalCredentials up to recommended and not deprecated (after discussion)
- Add `get_client_from_auth_file`
This integrates update in https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/74, to avoid too many unecessary conflict in the future.

Improve Authentication page

---

docs-ref-conceptual/python-sdk-azure-authenticate.md

Fix base url for authentication to sovereign clouds.
This is in reference to a support incident I recently filed with Microsoft. The `<sov_cloud>.endpoints.resource_manager` is the appropriate `base_url` for all `*Client` objects in the SDK.

demonstrate correct base_url

---

docs-ref-services/servicebus.md

Actual dependency used in the code samples looks to be this one: https://github.com/Azure/azure-sdk-for-python/tree/master/azure-servicebus
Not this one: https://github.com/Azure/azure-sdk-for-python/tree/master/azure-mgmt-servicebus
Installing the one recommended by the docs resulted in `ImportError` for me.

Docs recommended installing *wrong* library

---

docs-ref-mapping/reference.yml
docs-ref-services/batchai.md

Azure Batch AI is deprecated, so we want to add a banner to the ref content explaining that.

BatchAI: Adding deprecation banner

---

docs-ref-mapping/reference.yml

Per @j-martens, the Machine Learning entry in the Azure Python SDK TOC can be removed as that content has been moved out of this repository.

[toc] Remove AML from reference.yml

---

docs-ref-services/storage.md

To make the example work, `PublicAccess` and `ContentSettings` have to be imported as well, otherwise Python complains that they're unknown. Tripped on that :)

Added missing imports to example

---

docs-ref-services/keyvault-secrets-readme.md

The azure-keyvault-keys GitHub link actually goes to the
azure-keyvault-secrets repository. Fix that and also provide a link to
the azure-keyvault-keys GitHub repository.

Fix azure-keyvault-keys GitHub link

---

docs-ref-services/storage-queue-readme.md

Python does not use 'new classname' to create an instance of an object.

fix syntax error for example

---

docs-ref-mapping/reference-unified.yml

Questions:
1. do we need `href` under top level? that is:
```
- name: Schema Registry
uid: azure.python.sdk.landingPage.services.SchemaRegistry
href: ~/docs-ref-services/schema-registry-index.md  # like storage or eh approach
```
answer: not for now, until we have manually written pages that describe SR service as a whole
2. If we need a `schema-registry-index.md`, what should be the content look like? storage, keyvault? (There are broken links in EH, we need to fix them)
- shall we update our github repo, to let top-level dir have a readme like storage?

Schema Registry

---

docs-ref-services/key-vault-index.md

This updates the "Reference" links for `azure-keyvault-certificates`, `azure-keyvault-keys`, `azure-keyvault-secrets`, and `azure-mgmt-keyvault` to point to their respective overview pages, instead of (versioned) pages on azuresdkdocs.blob.core.windows.net.

Update reference links on KV index

---

docs-ref-mapping/reference-unified.yml

`azure-synapse` was being excluded from the `Synapse` service due to ToC config only include `azure-synapse-` prefixed packages.

Fix Synapse Mapping

---

docs-ref-mapping/reference-previous.yml

Below files will be published to same url, please help fix this issue by either adding `href` to TopLevelTocItem or removing/renaming the existing markdown files. 
| site url | existing markdown file | generated service page for TopLevelToc |
| --- | --- | --- |
| /python/api/overview/azure/servicebus | [docs-ref-services/legacy/servicebus.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/legacy/servicebus.md) | [previous/docs-ref-autogen/overview/azure/ServiceBus.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-mapping/reference-previous.yml#L16-L17) |
| /python/api/overview/azure/other | [docs-ref-services/legacy/other.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/legacy/othe …

Try to resolve duplicate output files

---

docs-ref-autogen/azure-mgmt-compute/azure.mgmt.compute.v2020_09_30.models.GalleryImage.yml

break tags are shown on the site for OS type - https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2020_09_30.models.galleryimage?view=azure-python
Removing these

Remove br tags from documentation

---

ci-configs/packages-latest.json

We had a patched version in there to repair the original `mgmt-servicebus 6.0.0`. It's been resolved in further releases, so just leaving the `pypi` one there.

Remove Duplicate `azure-mgmt-servicebus`

---

docs-ref-services/latest/containerinstance.md

https://docs.microsoft.com/en-us/python/api/overview/azure/containerinstance?view=azure-python
#PingMSFTDocs

Typo "Azure container instances"→"Azure Container Instances"

---

docfx.json

Autogenerated reference topics are supposed to be 'managed-reference' as opposed to reference.  Updating docfx to reflect this.

Update topic type to managed-reference

---

docs-ref-services/latest/containerinstance.md

RE: https://github.com/Azure/azure-sdk-for-python/issues/19131
A GitHub issue pointed out some of the API links in this article were broken. This PR fixes.

API URL fixes

---

docs-ref-services/preview/purview-scanning-readme.md

The correct url needs to be changed from `.scanning.purview.azure.com` to `.scan.purview.azure.com`.
Reference: https://docs.microsoft.com/en-us/rest/api/purview/scanningdataplane/scans/get

Fixing wrong endpoint url scanning.azure.com

---

docs-ref-services/latest/containerinstance.md
docs-ref-services/latest/hdinsight.md
docs-ref-services/legacy/containerinstance.md
docs-ref-services/legacy/hdinsight.md
docs-ref-services/preview/containerinstance.md
docs-ref-services/preview/hdinsight.md

Default role: Contributor is being deprecated for az ad sp create-for-rbac. Added --role contributor to code blocks where the current role selection is left as default (no parameter). Added CLI code block tags where missing in containerinstance files.
User story [1876839](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1876839)

1876839: Add CLI contributor role to code blocks

---

docs-ref-mapping/reference-unified.yml

**Summary of changes**
- Rename "Monitoring" ToC node to "Monitor"
- Rename "Client" ToC node to "OpenTelemetry Exporter"
- Move Monitor Query APIs to the "Monitor" ToC node

Reorganize Monitor APIs in ToC

---

docs-ref-services/latest/logic-apps.md

The Explore Management APIs button is redirecting to an incorrect link.
Old Link: https://docs.microsoft.com/en-us/python/api/overview/azure/logicapps/management
New Link: https://docs.microsoft.com/en-us/python/api/azure-mgmt-logic
Fixes Azure/azure-sdk-for-python#24662

{LogicApp} Fixes Azure/azure-sdk-for-python#24662

---

docs-ref-services/latest/iot.md

This issue fixes the function name of IoTHub Client
fixes Azure/azure-sdk-for-python#28891

{AzureIoT} fixes Azure/azure-sdk-for-python#28891 Updating the function name

---

docs-ref-services/latest/iot.md
docs-ref-services/legacy/iot.md
docs-ref-services/preview/iot.md

The management API link is incorrect. It currently leads to 404 error.
Old Link: /python/api/overview/azure/iot/management
New Link: /python/api/overview/azure/mgmt-iothub-readme
fixes Azure/azure-sdk-for-python#29309

{AzureIOT} Fix the broken Management API link for IOT package

---

.openpublishing.publish.config.json

open_to_public_contributors was set to true which allows edits, set to false to disable.
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/29671

Disable edit button on learn.microsoft.com for Python

---

ci-configs/packages-latest.json

Currently, `azure-functions` and `azure-functions-durable` have out of date auto-generated docs. This appears to be due to the code source being on blob storage, instead of pulling from PyPI.
This PR aims to change this behavior so that the source code for these packages is pulled directly from the latest release on PyPI
@danieljurek, @gavin-aguiar

Pull azure-functions and azure-functions-durable from PyPI

---

ci-configs/packages-preview.json

Example successful build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=364533&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=1e77462e-7711-551f-cf20-c31b880b493a -- note "preview" had no `prefer_source_distribution` entry (latest does, and it failed)

Readd azure-iot-device, omitting the "prefer_source_distribution" entry. We need a way to know the right value to provide here going forward.

---

bread/toc.yml
docfx.json

This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation.

Fix breadcrumbs

---

metadata/preview/azureml-featurestore.json

Onboard azureml-featurestore package, which is not published via azure-sdk pipeline.
Related PR: https://github.com/Azure/azure-sdk/pull/6914

Onboard azureml-featurestore to doc gen

---

docs-ref-services/latest/keyvault-secrets-readme.md
metadata/latest/azure-keyvault-secrets.json

`azure-keyvault-secrets` version 4.8.0 was [successfully released](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3520076&view=results) yesterday, but the ESRP publishing stage erroneously raised an error. This caused other steps, like docs publishing, to get skipped. This PR manually updates docs metadata accordingly.
Based on updates to other KV libraries, e.g. https://github.com/MicrosoftDocs/azure-docs-sdk-python/commit/b98409e3758dafd5bed3ca1095d9aa4494dc3166
The diff displayed here is excessive because of line ending changes; here's a more accurate diff showing that the only updates are to metadata, README content updates (minimum Python version and sample link updates), and links to the Python repo (updating the release tag): https://www.diffchecker.com/ef9mbiIK/

Update docs metadata for release of `azure-keyvault-secrets`

---

.openpublishing.publish.config.json
redirections/.openpublishing.redirection.simplify-package-structure.json

Add `.openpublishing.redirection.simplify-package-structure.json` containing redirections from previously distribution level pages (now removed from main branch) to top level namespaces.

Add redirections for simplifying TOC has removed distribution level pages

---

docsms-allowlist/python-allowlist.txt

The azure-sdk team has an [automated pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5213&_a=summary) which merges main->live every Wednesday at 4am PDT. Each repository has a <lang>-allowlist.txt file which includes patterns that are safe to merge. docfx.json is not in this list, mainly because there were two live site incidents related to changes to docfx.json. Recently, the pipelines have blocked merges because of changes to docfx.json which have been coming from other automated Learn sources. @nickwalkmsft and I chatted and decided to relax the restriction and allow changes to docfx.json to be merged.
This same change is being made to the following docs repositories:
- Azure/azure-docs-sdk-dotnet
- Azure/azure-docs-sdk-java
- MicrosoftDocs/azure-docs-sdk-node
- …

Add docfx.json to the allow list for automatic merging from main->live

---

docsms-allowlist/python-allowlist.txt

My preview PR updated the allow list and that change failed the auto-merge. The allow list isn't a file that's often updated and, even then, is only updated by hand, not automation. Don't prevent the auto-merge from main->live for allow list changes.

Add docsms-allowlist directory to allow list for the repository

---

docs-ref-services/latest/cognitive-services.md

azure-cognitiveservices-language-textanalytics is deprecated and is now azure-ai-textanalytics. The **Learn More** and **Quickstart** links already redirect to the azure-ai-textanalytics docs. The **Try the Text Analytics API** also redirects but it's slower so you see the original link before it redirects to the new service. Because of that I'm updating this.

Update pip install and try link for textanalytics

---

ci-configs/packages-latest.json
ci-configs/packages-preview.json

This PR is due to https://dev.azure.com/ceapex/Engineering/_workitems/edit/1000880. This was tested in the pipeline with 1.47.0 (it's in that linked issue) however 1.47.1 was released this morning. I also checked with the owner of python owner azure-ai-* and anything openai > 1.0.0 should work jsut fine.

Update openai dependency

---

ci-configs/packages-latest.json
ci-configs/packages-preview.json

Apparently, the [content feeds](https://apidrop.visualstudio.com/Content%20CI/_artifacts/feed/Content_CI_PublicPackages/PyPI/openai/versions/1.47.0) take a while to get newer versions and 1.47.1 was released this morning and hasn't updated. Setting this to the latest released version since 1.47.0 doesn't matter.

Set openai to 1.47.0

---

metadata/latest/azure-cognitiveservices-speech.json

Reverts MicrosoftDocs/azure-docs-sdk-python#2010
There was a failure during last week's build which could be attributable to the speech package but it builds correctly in isolation. 
Failure: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=565446&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=82308bed-e88c-552e-8a03-cd3f5b3ab7a3
Isolated build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=567719&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=82308bed-e88c-552e-8a03-cd3f5b3ab7a3

Revert "Revert "Update speech SDK for 1.46.0""
